name: Prepare Release PR

on:
  push:
    branches:
      - 'release-*'

jobs:
  prepare-release:
    uses: mgeisler/rust-release-gh-action/.github/workflows/prepare-release.yml@main
    with:
      name: "Martin Geisler"
      email: "martin@geisler.net"
      changelog-file: "README.md"
      changelog-heading-level: "###"
