name: Continuous integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - run: cargo build --no-default-features
      - run: cargo test --lib --no-default-features --features english
      - run: cargo test --lib
      - run: cargo test --test generate
