name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: --cfg=docsrs -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo check --features alloc
      - run: cargo check --features std
      - run: cargo check --features async
      - run: cargo check --features alloc,async
      - run: cargo check --features std,async
      - run: cargo check --features tokio
      - run: cargo check --features futures
      - run: cargo check --features tokio,futures
      - run: RUSTUP_TOOLCHAIN=stable cargo check
      - run: RUSTUP_TOOLCHAIN=stable cargo check --features alloc
      - run: RUSTUP_TOOLCHAIN=stable cargo check --features std
      - run: cargo rustdoc --features std,async,defmt,tokio,futures